version: '3.9'

services:
  nginx:
    container_name: web-nginx
    image: nginx:1.22.1
    volumes:
      - ./:/var/www/html
      - ./docker-conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-conf/nginx/conf.d/local-test.conf:/etc/nginx/conf.d/local-test.conf
    depends_on:
      - front
    ports:
      - "80:80"
  front:
    container_name: next-tailwind-frontend
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app