import Head from "next/head";
import type { NextPage, GetServerSideProps } from 'next';
import styles from "@/styles/Home.module.css";

type User = {
  username: string;
  email: string;
  bio: string;
}

type Props = {
  user: User
}

const Page: NextPage<Props> = ({user}) => {
  console.log('data: ', user);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div>Page Router</div>
        <div>username: {user.username}</div>
        <div>email: {user.email}</div>
        <div>bio: {user.bio}</div>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const response = await fetch('http://pizza.local.com/api/user', {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  })

  const data = await response.json();

  return {
    props: {
      user: data.user
    }
  }
}

export default Page;