version: '3'
services:
  php_service:
    container_name: php_container
    build: ./
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8080
    volumes:
      - './:/var/www/html'
    ports:
      - '8080:8080'
