version: "3"

services:
  api-service:
    build: ./
    command: "/app/api-service"
    depends_on:
      - db-mysql
    environment:
      - DB_ADDR=${DB_ADDR}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./src:/app/src
  db-mysql:
    container_name: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: