name: open-next ci with private packages

on:
  pull_request:
    paths:
      - 'open-next-with-aws/**'

defaults:
  run:
    working-directory: open-next-with-aws/frontend

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Generate apps token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.SCHEMA_APP_ID }}
          private_key: ${{ secrets.SCHEMA_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          persist-credentials: false
      - name: Configure Git
        run: git config --global --add url."https://${{ steps.generate_token.outputs.token }}@github.com/".insteadOf "https://github.com/"
      - name: check secrets
        run: echo "${{secrets.TEST}}"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: echo node version
        run: node --version
      - name: Cache node_modules
        id: cache_node_modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci 
