name: "Release Tag"

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Tokyo

jobs:
  main:
    name: Create Release Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set tag name
        id: tag
        run: |
          IMAGE_TAG="$(date +"%Y.%m.%-d").$(git tag | (grep "^`date +"%Y.%m.%-d"`" || true) | wc -l | awk '{print $1+1}')"
          echo "::set-output name=tag::${IMAGE_TAG}"
      - name: Get merged PRs
        id: prs
        run: |
          PR_LIST=""
          for PR_NUMBER in $(git log --ancestry-path --oneline $(git rev-list --tags --max-count=1).. | grep -o '#[0-9]\+' | tr -d '#'); do
            PR_LIST+=$(gh pr view $PR_NUMBER --json title,url --jq '"- [\(.title)](\(.url))"')
            PR_LIST+=$'\n'
          done
          echo "::set-output name=list::$PR_LIST"       
      - name: Create Release Tag
        run: |
          TAG_NAME=${{ steps.tag.outputs.tag }}
          PR_LIST=${{ steps.prs.outputs.list }}

