name: "Release Tag"

on:
  workflow_dispatch:

jobs:
  main:
    name: Create Release Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set tag name
        id: tag
        run: echo "::set-output name=tag::v$(date +'%Y%m%d')-1"
      - name: Create Release Tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Release ${{ steps.tag.outputs.tag }}
          body: |
            This is a release tag for version ${{ steps.tag.outputs.tag }}
